export { DocsPage } from './Docs'
export { LeaderboardPage } from './Leaderboard'
export { AutoSettlePage } from './AutoSettle'
export { CrossChainPage } from './CrossChain'
export { LandingPage } from './Landing'
